### ISSUE TITLE
Send too many packets even with tracking-warning-pps: 500

### ISSUE THREAD

**Issue by titidelaff** [PluginBugs/Issues-CinematicStudio#60]
### Terms

- [X] I'm using the very latest version of CinematicsStudio and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CinematicsStudio/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cinematicstudio) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

titidelaff

### What happened?

Play scene and getting kick with Send too many packets.
Try set tracking-warning-pps: 500 as said in the faq

### Steps to reproduce the issue

setup scene
play scene
get kick

### Server version

Paper version git-Paper-193 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 581b683)

### CinematicsStudio Version

CinematicStudio version 1.4.5

### ProtocolLib Version

5.1.1-SNAPSHOT-669

### LoneLibs Version

1.0.27

**Comment by LoneDev6** [comment]
Please send a screenshot of the error shown in the game screen and check if your logs contain errors and send them here.
